# Generated by Django 3.2.4 on 2022-09-01 01:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='deputy_governor',
            field=models.CharField(help_text='Name of the assistant class representative', max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='governor',
            field=models.CharField(help_text='Name of the class representative', max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.CharField(choices=[('100 Level', 'Level100'), ('200 Level', 'Level200'), ('300 Level', 'Level300'), ('400 Level', 'Level400'), ('500 Level', 'Level500')], max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='class',
            name='session',
            field=models.CharField(choices=[('2018/19', 'Y2018'), ('2019/20', 'Y2019'), ('2020/21', 'Y2020'), ('2021/22', 'Y2021'), ('2022/23', 'Y2022'), ('2023/24', 'Y2023'), ('2024/25', 'Y2024')], max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, help_text='external id used to identify each class', unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.class'),
        ),
    ]
